apiVersion: v1
kind: Service
metadata:
  name: rolaxresorts-service
  labels:
    app: rolaxresorts
spec:
  selector:
    app: rolaxresorts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer